### ISSUE TITLE
torch dataloader crashed after `set_up_backend` 

### ISSUE THREAD

**Issue by jk4011** [esa/torchquad#157] opened 2022-08-31 04:59 UTC
# Issue
## Problem Description
I'm using this torch integration for deep learning model training. 
If I add this line `set_up_backend("torch")` or `set_up_backend("torch", data_type="float32")`, I get error at [torch dataloader](https://pytorch.org/docs/stable/data.html). I have no idea why this line make dataloader broken. Do you have any idea about this error?

### Error message
```
  File "/home/wlsgur4011/torchlevy/test/data_loader_conflict.py", line 21, in test_data_loader_confliict
    for x in train_loader:
  File "/home/wlsgur4011/.anaconda3/envs/torchlevy/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/wlsgur4011/.anaconda3/envs/torchlevy/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 720, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "/home/wlsgur4011/.anaconda3/envs/torchlevy/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 671, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/wlsgur4011/.anaconda3/envs/torchlevy/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 247, in __iter__
    for idx in self.sampler:
  File "/home/wlsgur4011/.anaconda3/envs/torchlevy/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 133, in __iter__
    yield from torch.randperm(n, generator=generator).tolist()[:self.num_samples % n]
RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'
```

Or can you give some explanation about `set_up_backend("torch")`? I cannot get any estimation how it works when I read the code. I found that [`logger.info("Active CUDA Device: GPU" + str(torch.cuda.current_device()))`](https://github.com/esa/torchquad/blob/bbbb3782cda4ff56f0e8093102dadaf87517b2a0/torchquad/utils/enable_cuda.py#L19)
this line influence gpu setting. If I remove this line, it works on cpu but not on gpu. I think it is just log code, and cannot understand how this code influences the gpu setting.

Thank you for reading this poor bug report.

**Comment by gomezzz** [comment] 2022-09-02 08:43
Hi @jk4011 !

Thanks for the bug report. So, my first suspicion would be that your data generator returns data that is on the CPU while you set up the default device to be GPU with set_up_backend("torch")?

Could you by any chance post a minimal code example to help me reproduce the problem? Then I would have a more detailed look.

Thanks!

**Comment by jk4011** [comment] 2022-09-07 13:18
Of course!
```
import torch
from torchquad import set_up_backend
from torchvision import datasets
from torch.utils.data import DataLoader

# this error only occurs when cuda is available
assert(torch.cuda.is_available())

set_up_backend('torch')

training_data = datasets.MNIST(
    root="data",
    train=True,
    download=True,
)

train_loader = DataLoader(training_data, batch_size=64, shuffle=True)

for (i, x) in enumerate(train_loader):
    pass
```

**Comment by gomezzz** [comment] 2022-10-10 08:18
Hi @jk4011 

Sorry for the late reply 🙏 Busy days

Just tried the snippet and indeed same happens for me. However, I think, the problem is due to a missing device specification.

See also [this stackoverflow post](https://stackoverflow.com/questions/68621210/runtimeerror-expected-a-cuda-device-type-for-generator-but-found-cpu)

Below snippet fixes the problem (and a follow-up one related to MNIST being PIL images) for me:

```Python

import torch
from torchquad import set_up_backend
from torchvision import datasets
from torch.utils.data import DataLoader
from torchvision import transforms

# this error only occurs when cuda is available
assert torch.cuda.is_available()

set_up_backend("torch")

transform = transforms.Compose(
    [
        # you can add other transformations in this list
        transforms.ToTensor()
    ]
)

training_data = datasets.MNIST(
    root="data", train=True, download=True, transform=transform
)

train_loader = DataLoader(
    training_data,
    batch_size=64,
    shuffle=True,
    generator=torch.Generator(device="cuda"),
)

for (i, x) in enumerate(train_loader):
    pass
```

Does it fix it for you too, @jk4011 ? :)

**Comment by gomezzz** [comment] 2022-10-18 09:49
Should be fixed / not a problem in torchquad

**Closed by gomezzz** 2022-10-18 09:49 UTC
Labels: bug
